### PR TITLE
Fault tolerance for eks deploy

### LINKED ISSUE #109: Fault tolerance in the eks deploy command
The eks deploy command should track where it is in the state of the deployment and recover from failures.

For example, it is fairly painful to recoup if the `deploy` command fails after the ASG was expanded and during the drain call. In that failure mode, the user has to manually drain all the nodes, and then terminate them. We should figure out a way for the `deploy` command to remember where it failed, and then provide the ability to retry starting from that step.

### PR DESCRIPTION
**Pull request by autero1**
## Description

This PR introduces fault tolerance for the `eks deploy` subcommand by introducing a recovery file for storing deploy state.
The `eks deploy` is split into multiple stages and the state file is updated after each stage:

1. Gather ASG info: Retrieve the ASG object and gather required info
2. Set ASG max capacity: Make sure there is enough max size capacity to scale up
3. Scale up: Launching new nodes with new launch config
4. Wait for new nodes: Wait for new nodes to be ready and verify everything is OK in k8s
5. Cordon nodes: Cordon old instances in cluster ASG
6. Drain nodes: Drain Pods on old instances
7. Detach instances: Remove old nodes from ASG
8. Terminate instances: Terminating detached instances
9. Restore ASG max capacity: Restore the ASG into original max capacity

The state file is generated into the working directory `./.kubergrunt.state` and persisted after each successful stage. If the `eks deploy` command fails for some reason, execution resumes from the last successful state. The existing recovery file can also be ignored with the `--ignore-recovery-file` flag. In this case the recovery file will be re-initialized.

The state is implemented with simple boolean flags instead of a state machine library. The stages in `eks deploy` are linear and there is no complex state handling, so a state machine library seemed overkill.

To better modularity and keeping action and verification stages separate, the `scaleUp` function is split into actual scale up and verification functions. This allows safer re-execution in case scale up was successful but verification fails for some reason.

### Other notable things

- Removing `defer setAsgMaxSize` and moving that to the last stage. If we're retrying using the recovery file, the original `defer` functionality could potentially lead to unexpected behaviour. I'm open for discussion on this, though.

- Kubernetes `drain` and `cordon` operations are still executed for the whole set of existing nodes - I assume these are idempotent and can safely be executed multiple times.

- As the AWS operations for detaching and terminating instances are batched, the command can still fail if previous detach, for example, was a partial success. Same applies to termination. Don't necessarily think this will be an issue

### Documentation

- README updated
- cli option documented

## TODOs

- [x] Ensure the branch is named correctly with the issue number. e.g: `feature/new-vpc-endpoints-955` or `bug/missing-count-param-434`.
- [x] Update the docs.
- [x] Keep the changes backwards compatible where possible.
- [x] Run the pre-commit checks successfully.
- [x] Run the relevant tests successfully.
- [x] Ensure any 3rd party code adheres with our license policy: https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378
- [ ] _Maintainers Only._ If necessary, release a new version of this repo.
- [ ] _Maintainers Only._ If there were backwards incompatible changes, include a migration guide in the release notes.
- [ ] _Maintainers Only._ Add to the next version of the monthly newsletter (see https://www.notion.so/gruntwork/Monthly-Newsletter-9198cbe7f8914d4abce23dca7b435f43).

## Related Issues

Fixes #109

### CODE REVIEW

File: eks/asg.go [hunk 1]
```diff
@@ -32,51 +32,68 @@ func GetAsgByName(svc *autoscaling.AutoScaling, asgName string) (*autoscaling.Gr
...
+
+	return newInstanceIds, nil
+}
+
+// scaleUp will scale the ASG up and wait until all the nodes are available. Specifically:
+// - Set the desired capacity on the ASG
+// - Wait for the capacity in the ASG to meet the desired capacity (instances are launched)
+// - Wait for the new instances to be ready in Kubernetes
+// - Wait for the new instances to be registered with external load balancers
+func waitAndVerifyNewInstances(
```
Comment (yorinasub17) [inline eks/asg.go:78]:
```suggestion
// waitAndVerifyNewInstances will scale the ASG up and wait until all the nodes are available. Specifically:
// - Wait for the capacity in the ASG to meet the desired capacity (instances are launched)
// - Wait for the new instances to be ready in Kubernetes
// - Wait for the new instances to be registered with external load balancers
func waitAndVerifyNewInstances(
```

File: eks/deploy.go [hunk 2]
```diff
@@ -57,112 +58,157 @@ func RollOutDeployment(
...
 	logger.Infof("Successfully authenticated with AWS")
 
-	// Retrieve the ASG object and gather required info we will need later
-	asgInfo, err := getAsgInfo(asgSvc, eksAsgName)
-	if err != nil {
-		return err
+	stateFile := defaultStateFile
+
+	// Retrieve state if one exists or construct a new one
+	state, err := readOrInitializeState(stateFile, ignoreRecoveryFile)
```
Comment (yorinasub17) [inline eks/deploy.go:64]: Missing error check?

File: eks/deploy.go [hunk 3]
```diff
@@ -57,112 +58,157 @@ func RollOutDeployment(
...
+
+	// If we're in the initial state, gather ASG info and wait for capacity
+	if !state.GatherASGInfoDone {
```
Comment (yorinasub17) [inline eks/deploy.go:67]: I think this if based state machine is fine, but perhaps it would make sense to encapsulate each stage as a method on the state machine struct for better maintainability? E.g.:

```
if !state.ActionDone {
  state.action()
}
```

This should hopefully make it easier to extend with additional state actions in the future.

File: eks/deploy.go [hunk 4]
```diff
@@ -57,112 +58,157 @@ func RollOutDeployment(
...
+
+		logger.Infof("Launching new nodes with new launch config on ASG %s", state.ASG.Name)
+		newInstanceIds, err := scaleUp(asgSvc, state.ASG.Name, state.ASG.OriginalInstances, state.ASG.MaxCapacityForUpdate, maxRetries, sleepBetweenRetries)
 		if err != nil {
-			logger.Error("Error waiting for ASG to reach steady state. Try again after the ASG is in a steady state.")
 			return err
 		}
-		logger.Infof("Verified ASG is in steady state (current capacity = desired capacity)")
-		asgInfo, err = getAsgInfo(asgSvc, eksAsgName)
+		logger.Infof("Successfully launched new nodes with new launch config on ASG %s", eksAsgName)
```
Comment (yorinasub17) [inline eks/deploy.go:131]:
```suggestion
		logger.Infof("Successfully scheduled to launch new nodes with new launch config on ASG %s", eksAsgName)
```

File: eks/deploy_state.go [hunk 5]
```diff
@@ -0,0 +1,92 @@
...
+	ScaleUpDone            bool
+	WaitForNodesDone       bool
+	CordonNodesDone        bool
+	DrainNodesDone         bool
+	DetachInstancesDone    bool
+	TerminateInstancesDone bool
+	RestoreCapacityDone    bool
+
+	Path string
+	ASG  ASG
```
Comment (yorinasub17) [inline eks/deploy_state.go:24]: NIT: This state assumes we are updating only a single ASG, which is true as of now, but in the future we want to be able to update multiple ASGs at once (see https://github.com/gruntwork-io/kubergrunt/issues/72). Consider future proofing the state struct to support this.

File: eks/deploy_state.go [hunk 6]
```diff
@@ -0,0 +1,92 @@
...
+
+func (state *DeployState) persist() {
+	file := state.Path
+	logger := logging.GetProjectLogger()
+	logger.Debugf("storing state file %s", file)
+
+	data, err := json.Marshal(state)
+
+	if err != nil {
+		logger.Fatalf("Error marshaling state: %v", err)
```
Comment (yorinasub17) [inline eks/deploy_state.go:65]: I think as a general pattern we try to avoid `Fatal` to shutdown the CLI. This is primarily because we would lose the stack trace error reporting we have in the framework ([here](https://github.com/gruntwork-io/go-commons/blob/master/entrypoint/entrypoint.go#L47)). Can you switch this to return the error (with stack trace) and handle it in the caller? I know that increases cyclomatic complexity, but it helps when debugging the errors (e.g., which action failed to persist the state?).

File: eks/deploy.go [hunk 7]
```diff
@@ -57,112 +58,157 @@ func RollOutDeployment(
...
+	}
+
+	if !state.WaitForNodesDone {
+		err := waitAndVerifyNewInstances(ec2Svc, elbSvc, elbv2Svc, state.ASG.NewInstances, kubectlOptions, maxRetries, sleepBetweenRetries)
 		if err != nil {
+			logger.Errorf("Error while waiting for new nodes to be ready.")
+			logger.Errorf("Either resume with the recovery file or terminate the new instances.")
 			return err
 		}
+		state.WaitForNodesDone = true
```
Comment (yorinasub17) [inline eks/deploy.go:144]:
```suggestion
		logger.Infof("Successfully confirmed new nodes were launched with new launch config on ASG %s", eksAsgName)
		state.WaitForNodesDone = true
```

File: eks/deploy.go [hunk 8]
```diff
@@ -57,112 +58,157 @@ func RollOutDeployment(
...
+		}
 	}
-	err = terminateInstances(ec2Svc, asgInfo.currentInstanceIDs)
+
+	err = state.delete()
 	if err != nil {
-		logger.Errorf("Error while terminating the old instances.")
-		logger.Errorf("Continue to terminate the underlying instances to complete the rollout.")
-		return err
+		logger.Errorf("Error deleting state file %s: %s", stateFile, err.Error())
```
Comment (yorinasub17) [inline eks/deploy.go:210]: I think this should be logged as a warning, and then include another log indicating that the user should manually remove the state file.

**Review by yorinasub17 — COMMENTED** [review]
General implementation and approach makes sense to me! I left a few comments with minor points.

Once those are addressed, I'll cut a temporary alpha release so we get a binary, and open a regression test PR in `terraform-aws-eks` so we can test the new functionality.

**Comment by autero1** [comment]
Thanks for the review. I reworked the logic quite a bit.

File: eks/deploy_state.go [hunk 9]
```diff
@@ -0,0 +1,323 @@
...
+}
+
+func newDeployState(path string) *DeployState {
+	return &DeployState{
+		Path: path,
+		ASGs: []ASG{},
+	}
+}
+
+func (state *DeployState) gatherASGInfo(asgSvc *autoscaling.AutoScaling, eksAsgNames []string) error {
```
Comment (yorinasub17) [inline eks/deploy_state.go:117]: NIT: Add function comments (this applies to all the action functions in this file)

**Review by yorinasub17 — COMMENTED** [review]
LGTM! The new updated style is much better! I only had minor nits left, but I think we are close!

File: eks/deploy_state.go (hunk 9 above)
Comment (autero1) [reply eks/deploy_state.go:129]: Fixed

File: eks/deploy_state.go [hunk 10]
```diff
@@ -0,0 +1,323 @@
...
+	// If we're in the initial state, gather ASG info and wait for capacity
+	if !state.GatherASGInfoDone {
```
[the remark this answers is not in the document]
Comment (autero1) [reply eks/deploy_state.go]: Fixed

**Review by yorinasub17 — COMMENTED** [review]
Updates LGTM! Will create an integration testing release that we can link to in `terraform-aws-eks` to kick off a test.

**Comment by yorinasub17** [comment]
Looks like there is a bug:

```
[] time="2022-01-10t21:49:15z" level=info msg="beginning roll out for eks cluster worker group eks-cluster-dnjdbl-additional-2022011021394957890000000d in us-east-1" name=kubergrunt
[] time="2022-01-10t21:49:15z" level=info msg="successfully authenticated with aws" name=kubergrunt
[] time="2022-01-10t21:49:15z" level=info msg="retrieving current asg info" name=kubergrunt
[] time="2022-01-10t21:49:15z" level=info msg="successfully retrieved current asg info." name=kubergrunt
[] time="2022-01-10t21:49:15z" level=info msg="\tcurrent desired capacity: 2" name=kubergrunt
[] time="2022-01-10t21:49:15z" level=info msg="\tcurrent max size: 4" name=kubergrunt
[] time="2022-01-10t21:49:15z" level=info msg="\tcurrent capacity: 2" name=kubergrunt
[] time="2022-01-10t21:49:15z" level=info msg="no max retries set. defaulted to 40 based on sleep between retries duration of 15s and scale up count 2." name=kubergrunt
[] time="2022-01-10t21:49:15z" level=info msg="starting with the following list of instances in asg:" name=kubergrunt
[] time="2022-01-10t21:49:15z" level=info msg="i-068c52a32617f04e0,i-0d31992bc468dc970" name=kubergrunt
[] time="2022-01-10t21:49:15z" level=info msg="launching new nodes with new launch config on asg eks-cluster-dnjdbl-additional-2022011021394957890000000d" name=kubergrunt
[] time="2022-01-10t21:49:15z" level=info msg="updating asg eks-cluster-dnjdbl-additional-2022011021394957890000000d desired capacity to 0." name=kubergrunt
[] time="2022-01-10t21:49:15z" level=error msg="failed to set asg capacity to 0" name=kubergrunt
[] time="2022-01-10t21:49:15z" level=error msg="if the capacity is set in aws, undo by lowering back to the original capacity. if the capacity is not yet set, triage the error message below and try again." name=kubergrunt
[] time="2022-01-10T21:49:15Z" level=error msg="*awserr.requestError ValidationError: New SetDesiredCapacity value 0 is below min value 2 for the AutoScalingGroup.\n\tstatus code: 400, request id: 15dece0b-6ee9-4257-a56e-42358af28475\n/home/circleci/project/eks/asg.go:153 (0x15710b1)\n/home/circleci/project/eks/asg.go:46 (0x15703b5)\n/home/circleci/project/eks/deploy_state.go:203 (0x1578ab6)\n/home/circleci/project/eks/deploy.go:72 (0x1576ee5)\n/home/circleci/project/cmd/eks.go:419 (0x158a5b1)\n/home/circleci/.go_workspace/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 (0x5e36e5)\n/home/circleci/.go_workspace/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174 (0x5e4459)\n/home/circleci/.go_workspace/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:407 (0x5e2454)\n/home/circleci/.go_workspace/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:373 (0x5e659f)\n/home/circleci/.go_workspace/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:102 (0x5e48f4)\n/home/circleci/.go_workspace/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:279 (0x5e1668)\n/home/circleci/.go_workspace/pkg/mod/github.com/gruntwork-io/go-commons@v0.8.2/entrypoint/entrypoint.go:35 (0x615a78)\n/home/circleci/project/cmd/main.go:66 (0x158c8a8)\n/usr/local/go/src/runtime/proc.go:225 (0x438ed6)\n\tmain: fn()\n/usr/local/go/src/runtime/asm_amd64.s:1371 (0x46c021)\n\tgoexit: BYTE\t$0x90\t// NOP\n" error="ValidationError: New SetDesiredCapacity value 0 is below min value 2 for the AutoScalingGroup.\n\tstatus code: 400, request id: 15dece0b-6ee9-4257-a56e-42358af28475"
 ```

**Comment by autero1** [comment]
Yes, I think `asg := state.ASGs[0]` is a value assignment rather than a reference. Since some of the stages mutate the `ASG` we should pass the reference, instead:  `asg := &state.ASGs[0]`

**Comment by yorinasub17** [comment]
Ah makes sense! Will cut a new test release and update the integration test branch.

**Comment by yorinasub17** [comment]
Integration testing build is here btw: https://app.circleci.com/pipelines/github/gruntwork-io/terraform-aws-eks/1698/workflows/9e334364-7615-4c6d-8e8e-cfdc8c5d4485

**Comment by autero1** [comment]
Not 100% sure the test failures were related. I kicked off the tests again.
https://app.circleci.com/pipelines/github/gruntwork-io/terraform-aws-eks/1698/workflows/4c25d48e-7f65-4dcc-a778-58290c6ad0ff

**Comment by autero1** [comment]
I discovered a bug while testing this manually with an existing EKS cluster. 

Since `maxRetries` is needed (and calculated) in `gatherASGInfo`, the calculated default value was lost for subsequent invocations due to the skip condition. If `--max-retries` option was omitted, the value was never re-calculated and was always set to 0, obviously leading to any stage relying on that to fail.

I fixed that by creating a method `ensureMaxRetries` that is invoked even when `GatherASGInfoDone` is `true`. This allows the user to override the value across retries.

The previous EKS module test was successful and now I've verified the functionality manually step by step, as well.

**Comment by rhoboat** [comment]
This is a cool feature. I look forward to reviewing it soon.

**Review by yorinasub17 — COMMENTED** [review]
Updates LGTM!

**Comment by yorinasub17** [comment]
Just kicked off another regression build: https://app.circleci.com/pipelines/github/gruntwork-io/terraform-aws-eks/1709/workflows/a947a9a8-3124-4190-9c4b-8d4cbcc329c9

If that passes, I think we can merge this in!

File: README.md [hunk 11]
```diff
@@ -256,6 +256,15 @@ Currently `kubergrunt` does not implement any checks for these resources to be i
...
 the user of any services that do not have a check.
 
+**`eks deploy` recovery file**
+
+Due to the nature of rolling update, the `deploy` subcommand performs multiple sequential actions that 
+depend on success of the previous operations. To mitigate intermittent failures, the `deploy` subcommand creates a
+recovery file in the working directory for storing current deploy state. The recovery file is updated after 
+each stage and if the `deploy` subcommand fails for some reason, execution resumes from the last successful state.
+The existing recovery file can also be ignored with the `--ignore-recovery-file` flag. In this case the recovery 
+file will be re-initialized.
```
Comment (rhoboat) [inline README.md:266]: So actually the existing recovery file will get blown out (overwritten)?

Comment (rhoboat) [reply README.md:266]: Hm, I'm thinking of other conventions for naming here. Does `ignore` imply that it won't create a recovery file? I can't think of a better name. 🤷

File: eks/deploy_state_test.go [hunk 12]
```diff
@@ -0,0 +1,101 @@
...
+	t.Parallel()
+	fileName := "./.na"
+	state, err := initDeployState(fileName, false, 3, 30*time.Second)
+	require.NoError(t, err)
+	defer os.Remove(fileName)
+
+	assert.Equal(t, fileName, state.Path)
+	assert.Equal(t, 3, state.maxRetries)
+	assert.Equal(t, 30*time.Second, state.sleepBetweenRetries)
+	assert.Equal(t, fileName, state.Path)
```
Comment (rhoboat) [inline eks/deploy_state_test.go:25]: Why check for this again?

**Review by rhoboat — APPROVED** [review]
LGTM, I just found one potential duplicate line in the test.

I really like how clean this is, where the deploy stages are neatly organized now.

File: eks/deploy_state.go [hunk 13]
```diff
@@ -0,0 +1,360 @@
...
+	if state.ScaleUpDone {
+		state.logger.Debug("Scale up already done - skipping")
+		return nil
+	}
+	asg := &state.ASGs[0]
+	state.logger.Info("Starting with the following list of instances in ASG:")
+	state.logger.Infof("%s", strings.Join(asg.OriginalInstances, ","))
+
+	state.logger.Infof("Launching new nodes with new launch config on ASG %s", asg.Name)
+	newInstanceIds, err := scaleUp(asgSvc, asg.Name, asg.OriginalInstances, asg.MaxCapacityForUpdate, state.maxRetries, state.sleepBetweenRetries)
```
Comment (rhoboat) [inline eks/deploy_state.go:215]: I just noticed this. How does Go know which `scaleUp` is being referred to here, is it via the parameters (the function signature)? We have a DeployState scaleUp and an ASG scaleUp.

Comment (yorinasub17) [reply eks/deploy_state.go:215]: The `scaleUp` function for `DeployState` is a method and not a function. E.g., it would call the `DeployState` version (and recurse) if this was `state.scaleUp`.

Comment (rhoboat) [reply eks/deploy_state.go:215]: Ah, right! Thank you.

**Review by yorinasub17 — DISMISSED** [review]
Regression build passed as well!

**Comment by autero1** [comment]
Thanks for the review! I removed the extra assertion, so think we're ready to release this now!

**Comment by autero1** [comment]
Thanks for the reviews! Merging this in now!
